package cn.omsfuk.compiling.support;

public enum Symbol {
    SYM_CONT, SYM_PROCEDURE, SYM_BEGIN, SYM_END, SYM_VAR, SYM_ODD, SYM_IF, SYM_THEN,
    SYM_CALL, SYM_WHILE, SYM_DO, SYM_READ, SYM_WRITE, SYM_PLUS, SYM_SUB, SYM_MUL, SYM_DIV,
    SYM_POUND, SYM_EQUAL, SYM_LESS, SYM_GREATER, SYM_LESS_EQUAL, SYM_GREATER_EQUAL,
    SYM_COMMA, SYM_SEMICOLON, SYM_LEFT_BRACKETS, SYM_RIGHT_BRACKETS, SYM_ASSIGN, SYM_PERIOD, SYM_NUMBER, SYM_IDENT
}
